### ISSUE TITLE
Could I use with "{{#ech data}}"?

### ISSUE THREAD

**Issue by thearabbit** [okgrow/meteor-promise#2]
I have like this

``` js
// Html
<ul>
      {{#each student}}
          <li>{{name}} | {{gender}}</li>
       {{/each}}
 </ul>

// Js
student: ReactivePromise(function () {
        return Meteor.promise("student");
    }, "loading...")

// Server method
Meteor.methods({
    student: function () {
        return Collection.Student.find({}).fetch();
    }
});
```

But don't work and don't show `loading...` for waiting.
Please help me.

**Comment by deanrad** [comment]
In place of `"loading..."` - if you want to display an `<li>` with some loading text in this case, you can provide: 

`[{name: "loading"}]`

where you currently provide the string `"loading..."`.. 

BTW Feel free to fork this repo and add your test cases to a folder so that I can try these things out easier.

**Comment by deanrad** [comment]
I verified that you can use any object in place of the loading message:

```
Template.example1Demo.helpers({
  arrayHelper: ReactivePromise(function () {
    return new Promise(function (resolve){
      setTimeout(resolve.bind({}, [{name: "A"}, {name: "B"}]), 2000)
    })
  }, [{name: "loading..."}])
});
```

and that will work with a template such as yours.
